# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/lwray/.brew/Cellar/cmake/3.22.3/bin/cmake

# The command to remove a file.
RM = /Users/lwray/.brew/Cellar/cmake/3.22.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lwray/Desktop/webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lwray/Desktop/webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/lwray/.brew/Cellar/cmake/3.22.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/lwray/.brew/Cellar/cmake/3.22.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lwray/Desktop/webserv/CMakeFiles /Users/lwray/Desktop/webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lwray/Desktop/webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserv

# Build rule for target.
webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserv
.PHONY : webserv

# fast build rule for target.
webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/build
.PHONY : webserv/fast

srcs/CGI/CGIRegister.o: srcs/CGI/CGIRegister.cpp.o
.PHONY : srcs/CGI/CGIRegister.o

# target to build an object file
srcs/CGI/CGIRegister.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/CGI/CGIRegister.cpp.o
.PHONY : srcs/CGI/CGIRegister.cpp.o

srcs/CGI/CGIRegister.i: srcs/CGI/CGIRegister.cpp.i
.PHONY : srcs/CGI/CGIRegister.i

# target to preprocess a source file
srcs/CGI/CGIRegister.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/CGI/CGIRegister.cpp.i
.PHONY : srcs/CGI/CGIRegister.cpp.i

srcs/CGI/CGIRegister.s: srcs/CGI/CGIRegister.cpp.s
.PHONY : srcs/CGI/CGIRegister.s

# target to generate assembly for a file
srcs/CGI/CGIRegister.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/CGI/CGIRegister.cpp.s
.PHONY : srcs/CGI/CGIRegister.cpp.s

srcs/CGI/CGIResponse.o: srcs/CGI/CGIResponse.cpp.o
.PHONY : srcs/CGI/CGIResponse.o

# target to build an object file
srcs/CGI/CGIResponse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/CGI/CGIResponse.cpp.o
.PHONY : srcs/CGI/CGIResponse.cpp.o

srcs/CGI/CGIResponse.i: srcs/CGI/CGIResponse.cpp.i
.PHONY : srcs/CGI/CGIResponse.i

# target to preprocess a source file
srcs/CGI/CGIResponse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/CGI/CGIResponse.cpp.i
.PHONY : srcs/CGI/CGIResponse.cpp.i

srcs/CGI/CGIResponse.s: srcs/CGI/CGIResponse.cpp.s
.PHONY : srcs/CGI/CGIResponse.s

# target to generate assembly for a file
srcs/CGI/CGIResponse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/CGI/CGIResponse.cpp.s
.PHONY : srcs/CGI/CGIResponse.cpp.s

srcs/config/configParser.o: srcs/config/configParser.cpp.o
.PHONY : srcs/config/configParser.o

# target to build an object file
srcs/config/configParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParser.cpp.o
.PHONY : srcs/config/configParser.cpp.o

srcs/config/configParser.i: srcs/config/configParser.cpp.i
.PHONY : srcs/config/configParser.i

# target to preprocess a source file
srcs/config/configParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParser.cpp.i
.PHONY : srcs/config/configParser.cpp.i

srcs/config/configParser.s: srcs/config/configParser.cpp.s
.PHONY : srcs/config/configParser.s

# target to generate assembly for a file
srcs/config/configParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParser.cpp.s
.PHONY : srcs/config/configParser.cpp.s

srcs/config/configParserLocation.o: srcs/config/configParserLocation.cpp.o
.PHONY : srcs/config/configParserLocation.o

# target to build an object file
srcs/config/configParserLocation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserLocation.cpp.o
.PHONY : srcs/config/configParserLocation.cpp.o

srcs/config/configParserLocation.i: srcs/config/configParserLocation.cpp.i
.PHONY : srcs/config/configParserLocation.i

# target to preprocess a source file
srcs/config/configParserLocation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserLocation.cpp.i
.PHONY : srcs/config/configParserLocation.cpp.i

srcs/config/configParserLocation.s: srcs/config/configParserLocation.cpp.s
.PHONY : srcs/config/configParserLocation.s

# target to generate assembly for a file
srcs/config/configParserLocation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserLocation.cpp.s
.PHONY : srcs/config/configParserLocation.cpp.s

srcs/config/configParserSetters.o: srcs/config/configParserSetters.cpp.o
.PHONY : srcs/config/configParserSetters.o

# target to build an object file
srcs/config/configParserSetters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserSetters.cpp.o
.PHONY : srcs/config/configParserSetters.cpp.o

srcs/config/configParserSetters.i: srcs/config/configParserSetters.cpp.i
.PHONY : srcs/config/configParserSetters.i

# target to preprocess a source file
srcs/config/configParserSetters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserSetters.cpp.i
.PHONY : srcs/config/configParserSetters.cpp.i

srcs/config/configParserSetters.s: srcs/config/configParserSetters.cpp.s
.PHONY : srcs/config/configParserSetters.s

# target to generate assembly for a file
srcs/config/configParserSetters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserSetters.cpp.s
.PHONY : srcs/config/configParserSetters.cpp.s

srcs/config/configParserUtils.o: srcs/config/configParserUtils.cpp.o
.PHONY : srcs/config/configParserUtils.o

# target to build an object file
srcs/config/configParserUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserUtils.cpp.o
.PHONY : srcs/config/configParserUtils.cpp.o

srcs/config/configParserUtils.i: srcs/config/configParserUtils.cpp.i
.PHONY : srcs/config/configParserUtils.i

# target to preprocess a source file
srcs/config/configParserUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserUtils.cpp.i
.PHONY : srcs/config/configParserUtils.cpp.i

srcs/config/configParserUtils.s: srcs/config/configParserUtils.cpp.s
.PHONY : srcs/config/configParserUtils.s

# target to generate assembly for a file
srcs/config/configParserUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/config/configParserUtils.cpp.s
.PHONY : srcs/config/configParserUtils.cpp.s

srcs/handler/autoindexing.o: srcs/handler/autoindexing.cpp.o
.PHONY : srcs/handler/autoindexing.o

# target to build an object file
srcs/handler/autoindexing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/autoindexing.cpp.o
.PHONY : srcs/handler/autoindexing.cpp.o

srcs/handler/autoindexing.i: srcs/handler/autoindexing.cpp.i
.PHONY : srcs/handler/autoindexing.i

# target to preprocess a source file
srcs/handler/autoindexing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/autoindexing.cpp.i
.PHONY : srcs/handler/autoindexing.cpp.i

srcs/handler/autoindexing.s: srcs/handler/autoindexing.cpp.s
.PHONY : srcs/handler/autoindexing.s

# target to generate assembly for a file
srcs/handler/autoindexing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/autoindexing.cpp.s
.PHONY : srcs/handler/autoindexing.cpp.s

srcs/handler/handler.o: srcs/handler/handler.cpp.o
.PHONY : srcs/handler/handler.o

# target to build an object file
srcs/handler/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/handler.cpp.o
.PHONY : srcs/handler/handler.cpp.o

srcs/handler/handler.i: srcs/handler/handler.cpp.i
.PHONY : srcs/handler/handler.i

# target to preprocess a source file
srcs/handler/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/handler.cpp.i
.PHONY : srcs/handler/handler.cpp.i

srcs/handler/handler.s: srcs/handler/handler.cpp.s
.PHONY : srcs/handler/handler.s

# target to generate assembly for a file
srcs/handler/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/handler.cpp.s
.PHONY : srcs/handler/handler.cpp.s

srcs/handler/handlerUtils.o: srcs/handler/handlerUtils.cpp.o
.PHONY : srcs/handler/handlerUtils.o

# target to build an object file
srcs/handler/handlerUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/handlerUtils.cpp.o
.PHONY : srcs/handler/handlerUtils.cpp.o

srcs/handler/handlerUtils.i: srcs/handler/handlerUtils.cpp.i
.PHONY : srcs/handler/handlerUtils.i

# target to preprocess a source file
srcs/handler/handlerUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/handlerUtils.cpp.i
.PHONY : srcs/handler/handlerUtils.cpp.i

srcs/handler/handlerUtils.s: srcs/handler/handlerUtils.cpp.s
.PHONY : srcs/handler/handlerUtils.s

# target to generate assembly for a file
srcs/handler/handlerUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/handler/handlerUtils.cpp.s
.PHONY : srcs/handler/handlerUtils.cpp.s

srcs/http/HTTPResponseMessage.o: srcs/http/HTTPResponseMessage.cpp.o
.PHONY : srcs/http/HTTPResponseMessage.o

# target to build an object file
srcs/http/HTTPResponseMessage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/HTTPResponseMessage.cpp.o
.PHONY : srcs/http/HTTPResponseMessage.cpp.o

srcs/http/HTTPResponseMessage.i: srcs/http/HTTPResponseMessage.cpp.i
.PHONY : srcs/http/HTTPResponseMessage.i

# target to preprocess a source file
srcs/http/HTTPResponseMessage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/HTTPResponseMessage.cpp.i
.PHONY : srcs/http/HTTPResponseMessage.cpp.i

srcs/http/HTTPResponseMessage.s: srcs/http/HTTPResponseMessage.cpp.s
.PHONY : srcs/http/HTTPResponseMessage.s

# target to generate assembly for a file
srcs/http/HTTPResponseMessage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/HTTPResponseMessage.cpp.s
.PHONY : srcs/http/HTTPResponseMessage.cpp.s

srcs/http/HTTPResponseMessageContentTypeMap.o: srcs/http/HTTPResponseMessageContentTypeMap.cpp.o
.PHONY : srcs/http/HTTPResponseMessageContentTypeMap.o

# target to build an object file
srcs/http/HTTPResponseMessageContentTypeMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/HTTPResponseMessageContentTypeMap.cpp.o
.PHONY : srcs/http/HTTPResponseMessageContentTypeMap.cpp.o

srcs/http/HTTPResponseMessageContentTypeMap.i: srcs/http/HTTPResponseMessageContentTypeMap.cpp.i
.PHONY : srcs/http/HTTPResponseMessageContentTypeMap.i

# target to preprocess a source file
srcs/http/HTTPResponseMessageContentTypeMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/HTTPResponseMessageContentTypeMap.cpp.i
.PHONY : srcs/http/HTTPResponseMessageContentTypeMap.cpp.i

srcs/http/HTTPResponseMessageContentTypeMap.s: srcs/http/HTTPResponseMessageContentTypeMap.cpp.s
.PHONY : srcs/http/HTTPResponseMessageContentTypeMap.s

# target to generate assembly for a file
srcs/http/HTTPResponseMessageContentTypeMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/HTTPResponseMessageContentTypeMap.cpp.s
.PHONY : srcs/http/HTTPResponseMessageContentTypeMap.cpp.s

srcs/http/Request.o: srcs/http/Request.cpp.o
.PHONY : srcs/http/Request.o

# target to build an object file
srcs/http/Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/Request.cpp.o
.PHONY : srcs/http/Request.cpp.o

srcs/http/Request.i: srcs/http/Request.cpp.i
.PHONY : srcs/http/Request.i

# target to preprocess a source file
srcs/http/Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/Request.cpp.i
.PHONY : srcs/http/Request.cpp.i

srcs/http/Request.s: srcs/http/Request.cpp.s
.PHONY : srcs/http/Request.s

# target to generate assembly for a file
srcs/http/Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/http/Request.cpp.s
.PHONY : srcs/http/Request.cpp.s

srcs/main.o: srcs/main.cpp.o
.PHONY : srcs/main.o

# target to build an object file
srcs/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/main.cpp.o
.PHONY : srcs/main.cpp.o

srcs/main.i: srcs/main.cpp.i
.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/main.cpp.i
.PHONY : srcs/main.cpp.i

srcs/main.s: srcs/main.cpp.s
.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/main.cpp.s
.PHONY : srcs/main.cpp.s

srcs/sockets/clientSocket.o: srcs/sockets/clientSocket.cpp.o
.PHONY : srcs/sockets/clientSocket.o

# target to build an object file
srcs/sockets/clientSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/clientSocket.cpp.o
.PHONY : srcs/sockets/clientSocket.cpp.o

srcs/sockets/clientSocket.i: srcs/sockets/clientSocket.cpp.i
.PHONY : srcs/sockets/clientSocket.i

# target to preprocess a source file
srcs/sockets/clientSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/clientSocket.cpp.i
.PHONY : srcs/sockets/clientSocket.cpp.i

srcs/sockets/clientSocket.s: srcs/sockets/clientSocket.cpp.s
.PHONY : srcs/sockets/clientSocket.s

# target to generate assembly for a file
srcs/sockets/clientSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/clientSocket.cpp.s
.PHONY : srcs/sockets/clientSocket.cpp.s

srcs/sockets/listeningSocket.o: srcs/sockets/listeningSocket.cpp.o
.PHONY : srcs/sockets/listeningSocket.o

# target to build an object file
srcs/sockets/listeningSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/listeningSocket.cpp.o
.PHONY : srcs/sockets/listeningSocket.cpp.o

srcs/sockets/listeningSocket.i: srcs/sockets/listeningSocket.cpp.i
.PHONY : srcs/sockets/listeningSocket.i

# target to preprocess a source file
srcs/sockets/listeningSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/listeningSocket.cpp.i
.PHONY : srcs/sockets/listeningSocket.cpp.i

srcs/sockets/listeningSocket.s: srcs/sockets/listeningSocket.cpp.s
.PHONY : srcs/sockets/listeningSocket.s

# target to generate assembly for a file
srcs/sockets/listeningSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/listeningSocket.cpp.s
.PHONY : srcs/sockets/listeningSocket.cpp.s

srcs/sockets/parentSocket.o: srcs/sockets/parentSocket.cpp.o
.PHONY : srcs/sockets/parentSocket.o

# target to build an object file
srcs/sockets/parentSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/parentSocket.cpp.o
.PHONY : srcs/sockets/parentSocket.cpp.o

srcs/sockets/parentSocket.i: srcs/sockets/parentSocket.cpp.i
.PHONY : srcs/sockets/parentSocket.i

# target to preprocess a source file
srcs/sockets/parentSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/parentSocket.cpp.i
.PHONY : srcs/sockets/parentSocket.cpp.i

srcs/sockets/parentSocket.s: srcs/sockets/parentSocket.cpp.s
.PHONY : srcs/sockets/parentSocket.s

# target to generate assembly for a file
srcs/sockets/parentSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/parentSocket.cpp.s
.PHONY : srcs/sockets/parentSocket.cpp.s

srcs/sockets/serverSocket.o: srcs/sockets/serverSocket.cpp.o
.PHONY : srcs/sockets/serverSocket.o

# target to build an object file
srcs/sockets/serverSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/serverSocket.cpp.o
.PHONY : srcs/sockets/serverSocket.cpp.o

srcs/sockets/serverSocket.i: srcs/sockets/serverSocket.cpp.i
.PHONY : srcs/sockets/serverSocket.i

# target to preprocess a source file
srcs/sockets/serverSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/serverSocket.cpp.i
.PHONY : srcs/sockets/serverSocket.cpp.i

srcs/sockets/serverSocket.s: srcs/sockets/serverSocket.cpp.s
.PHONY : srcs/sockets/serverSocket.s

# target to generate assembly for a file
srcs/sockets/serverSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/serverSocket.cpp.s
.PHONY : srcs/sockets/serverSocket.cpp.s

srcs/sockets/socketData.o: srcs/sockets/socketData.cpp.o
.PHONY : srcs/sockets/socketData.o

# target to build an object file
srcs/sockets/socketData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/socketData.cpp.o
.PHONY : srcs/sockets/socketData.cpp.o

srcs/sockets/socketData.i: srcs/sockets/socketData.cpp.i
.PHONY : srcs/sockets/socketData.i

# target to preprocess a source file
srcs/sockets/socketData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/socketData.cpp.i
.PHONY : srcs/sockets/socketData.cpp.i

srcs/sockets/socketData.s: srcs/sockets/socketData.cpp.s
.PHONY : srcs/sockets/socketData.s

# target to generate assembly for a file
srcs/sockets/socketData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/sockets/socketData.cpp.s
.PHONY : srcs/sockets/socketData.cpp.s

srcs/utils/dataStructs.o: srcs/utils/dataStructs.cpp.o
.PHONY : srcs/utils/dataStructs.o

# target to build an object file
srcs/utils/dataStructs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/utils/dataStructs.cpp.o
.PHONY : srcs/utils/dataStructs.cpp.o

srcs/utils/dataStructs.i: srcs/utils/dataStructs.cpp.i
.PHONY : srcs/utils/dataStructs.i

# target to preprocess a source file
srcs/utils/dataStructs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/utils/dataStructs.cpp.i
.PHONY : srcs/utils/dataStructs.cpp.i

srcs/utils/dataStructs.s: srcs/utils/dataStructs.cpp.s
.PHONY : srcs/utils/dataStructs.s

# target to generate assembly for a file
srcs/utils/dataStructs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/utils/dataStructs.cpp.s
.PHONY : srcs/utils/dataStructs.cpp.s

srcs/webserver/accepter.o: srcs/webserver/accepter.cpp.o
.PHONY : srcs/webserver/accepter.o

# target to build an object file
srcs/webserver/accepter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/accepter.cpp.o
.PHONY : srcs/webserver/accepter.cpp.o

srcs/webserver/accepter.i: srcs/webserver/accepter.cpp.i
.PHONY : srcs/webserver/accepter.i

# target to preprocess a source file
srcs/webserver/accepter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/accepter.cpp.i
.PHONY : srcs/webserver/accepter.cpp.i

srcs/webserver/accepter.s: srcs/webserver/accepter.cpp.s
.PHONY : srcs/webserver/accepter.s

# target to generate assembly for a file
srcs/webserver/accepter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/accepter.cpp.s
.PHONY : srcs/webserver/accepter.cpp.s

srcs/webserver/responder.o: srcs/webserver/responder.cpp.o
.PHONY : srcs/webserver/responder.o

# target to build an object file
srcs/webserver/responder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/responder.cpp.o
.PHONY : srcs/webserver/responder.cpp.o

srcs/webserver/responder.i: srcs/webserver/responder.cpp.i
.PHONY : srcs/webserver/responder.i

# target to preprocess a source file
srcs/webserver/responder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/responder.cpp.i
.PHONY : srcs/webserver/responder.cpp.i

srcs/webserver/responder.s: srcs/webserver/responder.cpp.s
.PHONY : srcs/webserver/responder.s

# target to generate assembly for a file
srcs/webserver/responder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/responder.cpp.s
.PHONY : srcs/webserver/responder.cpp.s

srcs/webserver/webserv.o: srcs/webserver/webserv.cpp.o
.PHONY : srcs/webserver/webserv.o

# target to build an object file
srcs/webserver/webserv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/webserv.cpp.o
.PHONY : srcs/webserver/webserv.cpp.o

srcs/webserver/webserv.i: srcs/webserver/webserv.cpp.i
.PHONY : srcs/webserver/webserv.i

# target to preprocess a source file
srcs/webserver/webserv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/webserv.cpp.i
.PHONY : srcs/webserver/webserv.cpp.i

srcs/webserver/webserv.s: srcs/webserver/webserv.cpp.s
.PHONY : srcs/webserver/webserv.s

# target to generate assembly for a file
srcs/webserver/webserv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/webserv.cpp.s
.PHONY : srcs/webserver/webserv.cpp.s

srcs/webserver/webservInit.o: srcs/webserver/webservInit.cpp.o
.PHONY : srcs/webserver/webservInit.o

# target to build an object file
srcs/webserver/webservInit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/webservInit.cpp.o
.PHONY : srcs/webserver/webservInit.cpp.o

srcs/webserver/webservInit.i: srcs/webserver/webservInit.cpp.i
.PHONY : srcs/webserver/webservInit.i

# target to preprocess a source file
srcs/webserver/webservInit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/webservInit.cpp.i
.PHONY : srcs/webserver/webservInit.cpp.i

srcs/webserver/webservInit.s: srcs/webserver/webservInit.cpp.s
.PHONY : srcs/webserver/webservInit.s

# target to generate assembly for a file
srcs/webserver/webservInit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/srcs/webserver/webservInit.cpp.s
.PHONY : srcs/webserver/webservInit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserv"
	@echo "... srcs/CGI/CGIRegister.o"
	@echo "... srcs/CGI/CGIRegister.i"
	@echo "... srcs/CGI/CGIRegister.s"
	@echo "... srcs/CGI/CGIResponse.o"
	@echo "... srcs/CGI/CGIResponse.i"
	@echo "... srcs/CGI/CGIResponse.s"
	@echo "... srcs/config/configParser.o"
	@echo "... srcs/config/configParser.i"
	@echo "... srcs/config/configParser.s"
	@echo "... srcs/config/configParserLocation.o"
	@echo "... srcs/config/configParserLocation.i"
	@echo "... srcs/config/configParserLocation.s"
	@echo "... srcs/config/configParserSetters.o"
	@echo "... srcs/config/configParserSetters.i"
	@echo "... srcs/config/configParserSetters.s"
	@echo "... srcs/config/configParserUtils.o"
	@echo "... srcs/config/configParserUtils.i"
	@echo "... srcs/config/configParserUtils.s"
	@echo "... srcs/handler/autoindexing.o"
	@echo "... srcs/handler/autoindexing.i"
	@echo "... srcs/handler/autoindexing.s"
	@echo "... srcs/handler/handler.o"
	@echo "... srcs/handler/handler.i"
	@echo "... srcs/handler/handler.s"
	@echo "... srcs/handler/handlerUtils.o"
	@echo "... srcs/handler/handlerUtils.i"
	@echo "... srcs/handler/handlerUtils.s"
	@echo "... srcs/http/HTTPResponseMessage.o"
	@echo "... srcs/http/HTTPResponseMessage.i"
	@echo "... srcs/http/HTTPResponseMessage.s"
	@echo "... srcs/http/HTTPResponseMessageContentTypeMap.o"
	@echo "... srcs/http/HTTPResponseMessageContentTypeMap.i"
	@echo "... srcs/http/HTTPResponseMessageContentTypeMap.s"
	@echo "... srcs/http/Request.o"
	@echo "... srcs/http/Request.i"
	@echo "... srcs/http/Request.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
	@echo "... srcs/sockets/clientSocket.o"
	@echo "... srcs/sockets/clientSocket.i"
	@echo "... srcs/sockets/clientSocket.s"
	@echo "... srcs/sockets/listeningSocket.o"
	@echo "... srcs/sockets/listeningSocket.i"
	@echo "... srcs/sockets/listeningSocket.s"
	@echo "... srcs/sockets/parentSocket.o"
	@echo "... srcs/sockets/parentSocket.i"
	@echo "... srcs/sockets/parentSocket.s"
	@echo "... srcs/sockets/serverSocket.o"
	@echo "... srcs/sockets/serverSocket.i"
	@echo "... srcs/sockets/serverSocket.s"
	@echo "... srcs/sockets/socketData.o"
	@echo "... srcs/sockets/socketData.i"
	@echo "... srcs/sockets/socketData.s"
	@echo "... srcs/utils/dataStructs.o"
	@echo "... srcs/utils/dataStructs.i"
	@echo "... srcs/utils/dataStructs.s"
	@echo "... srcs/webserver/accepter.o"
	@echo "... srcs/webserver/accepter.i"
	@echo "... srcs/webserver/accepter.s"
	@echo "... srcs/webserver/responder.o"
	@echo "... srcs/webserver/responder.i"
	@echo "... srcs/webserver/responder.s"
	@echo "... srcs/webserver/webserv.o"
	@echo "... srcs/webserver/webserv.i"
	@echo "... srcs/webserver/webserv.s"
	@echo "... srcs/webserver/webservInit.o"
	@echo "... srcs/webserver/webservInit.i"
	@echo "... srcs/webserver/webservInit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

