#!/usr/bin/python

import datetime, os

e = datetime.datetime.now()

print ( "#!/usr/bin/python")

# print ( os.getenv('USER_NAME') )

print ("time generated by ret_time.py")

print (e.strftime("%d/%m/%Y"))

print (e.strftime("%I:%M:%S %p"))

